name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "Setting up environment variables"
        echo "DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}" >> $GITHUB_ENV
        echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

  tests:
    needs: main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Install docker-compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose
    - name: Run Integration tests
      run: |
        # Запуск docker-compose для тестового окружения
        docker-compose -f docker-compose.test.yml up -d
        # Ожидание готовности сервисов
        sleep 30
        # Выполнение тестов
        docker exec security-monitor pytest /app/tests/
        # Проверка простой логики
        echo "Running simple test: 1 + 1 = 2"
        python -c "assert 1 + 1 == 2, 'Test failed: 1 + 1 does not equal 2'"
        # Очистка
        docker-compose -f docker-compose.test.yml down
