name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "Setting up environment variables"
        echo "DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}" >> $GITHUB_ENV
        echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

  tests:
    needs: main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Install docker-compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose
    - name: Run Integration tests
      run: |
        docker-compose -f ./docker-compose.test.yml up -d  #<-- Verify path here
        sleep 30
        docker exec security-monitor pytest /app/tests/
        echo "Running simple test: 1 + 1 = 2"
        python -c "assert 1 + 1 == 2, 'Test failed: 1 + 1 does not equal 2'"
        docker-compose -f ./docker-compose.test.yml down


  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Suricata Image
      uses: docker/build-push-action@v4
      with:
        context: ./suricata
        tags: ${{ env.DOCKER_REGISTRY }}/suricata:${{ env.VERSION }}
        push: true
    - name: Build PostgreSQL Image
      uses: docker/build-push-action@v4
      with:
        context: ./postgresql
        tags: ${{ env.DOCKER_REGISTRY }}/postgresql:${{ env.VERSION }}
        push: true
    - name: Build Nginx Image
      uses: docker/build-push-action@v4
      with:
        context: ./nginx
        tags: ${{ env.DOCKER_REGISTRY }}/nginx:${{ env.VERSION }}
        push: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Access remote server
      uses: appleboy/ssh-action@v0.1.17
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
    - name: Pull and Deploy Services
      run: |
        ssh -i ${{ secrets.SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker-compose down
        sed -i "s/{{VERSION}}/${{ env.VERSION }}/g" docker-compose.yml
        docker-compose up -d --build
        docker ps
        EOF
